In [13]:
import pandas as pd
from openai import OpenAI
from data_analysis import get_clean_data
import mplfinance as mpf

df_all = get_clean_data()
print(type(df_all))

ModuleNotFoundError: No module named 'mplfinance'

In [2]:
df_nvda = get_clean_data()['nvda']
print(type(df_nvda))

print(df_nvda.index)
print(df_nvda)

df_amzn = get_clean_data()['amzn']

# df_nvda['company_name']
print(df_nvda.columns.tolist())

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex(['2018-01-02', '2018-01-03', '2018-01-04', '2018-01-05',
               '2018-01-08', '2018-01-09', '2018-01-10', '2018-01-11',
               '2018-01-12', '2018-01-16',
               ...
               '2024-10-09', '2024-10-10', '2024-10-11', '2024-10-14',
               '2024-10-15', '2024-10-16', '2024-10-17', '2024-10-18',
               '2024-10-21', '2024-10-22'],
              dtype='datetime64[ns]', name='Date', length=1713, freq=None)
                  Open        High         Low       Close   Adj Close  \
Date
2018-01-02    4.894500    4.987500    4.862500    4.983750    4.930221
2018-01-03    5.102500    5.342500    5.093750    5.311750    5.254698
2018-01-04    5.394000    5.451250    5.317250    5.339750    5.282397
2018-01-05    5.354750    5.422750    5.277000    5.385000    5.327161
2018-01-08    5.510000    5.625000    5.464500    5.550000    5.490389
...                ...         ...         ...         ...         ...
2024-10-16  133.979996  136.619995  131.580002  135.720001  135.720001
2024-10-17  139.339996  140.889999  136.869995  136.929993  136.929993
2024-10-18  138.669998  138.899994  137.279999  138.000000  138.000000
2024-10-21  138.130005  143.710007  138.000000  143.710007  143.710007
2024-10-22  142.919998  144.419998  141.779999  143.589996  143.589996

               Volume company_name
Date
2018-01-02  355616000       Nvidia
2018-01-03  914704000       Nvidia
2018-01-04  583268000       Nvidia
2018-01-05  580124000       Nvidia
2018-01-08  881216000       Nvidia
...               ...          ...
2024-10-16  264879700       Nvidia
2024-10-17  306435900       Nvidia
2024-10-18  176090200       Nvidia
2024-10-21  264554500       Nvidia
2024-10-22  223043755       Nvidia

[1713 rows x 7 columns]
['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', 'company_name']

In [3]:
df_nvda

,Open,High,Low,Close,Adj Close,Volume,company_name
Date,,,,,,,
2018-01-02,4.894500,4.987500,4.862500,4.983750,4.930221,355616000,Nvidia
2018-01-03,5.102500,5.342500,5.093750,5.311750,5.254698,914704000,Nvidia
2018-01-04,5.394000,5.451250,5.317250,5.339750,5.282397,583268000,Nvidia
2018-01-05,5.354750,5.422750,5.277000,5.385000,5.327161,580124000,Nvidia
2018-01-08,5.510000,5.625000,5.464500,5.550000,5.490389,881216000,Nvidia
...,...,...,...,...,...,...,...
2024-10-16,133.979996,136.619995,131.580002,135.720001,135.720001,264879700,Nvidia
2024-10-17,139.339996,140.889999,136.869995,136.929993,136.929993,306435900,Nvidia
2024-10-18,138.669998,138.899994,137.279999,138.000000,138.000000,176090200,Nvidia
2024-10-21,138.130005,143.710007,138.000000,143.710007,143.710007,264554500,Nvidia
2024-10-22,142.919998,144.419998,141.779999,143.589996,143.589996,223043755,Nvidia

In [4]:
print(type(df_all))
print(type(df_nvda))

for key in df_all.keys():
    print(key)

print(df_nvda.items())
print(df_nvda.size)
df_nvda
df_amzn
#print(df_all.head())

<class 'dict'>
<class 'pandas.core.frame.DataFrame'>
nvda
tsla
amzn
msft
cost
gme
pfe
lly
<generator object DataFrame.items at 0x165900f90>
11991

,Open,High,Low,Close,Adj Close,Volume,company_name
Date,,,,,,,
2018-01-02,58.599998,59.500000,58.525501,59.450500,59.450500,53890000,Amazon
2018-01-03,59.415001,60.274502,59.415001,60.209999,60.209999,62176000,Amazon
2018-01-04,60.250000,60.793499,60.233002,60.479500,60.479500,60442000,Amazon
2018-01-05,60.875500,61.457001,60.500000,61.457001,61.457001,70894000,Amazon
2018-01-08,61.799999,62.653999,61.601501,62.343498,62.343498,85590000,Amazon
...,...,...,...,...,...,...,...
2024-10-16,187.050003,187.779999,185.610001,186.889999,186.889999,23456800,Amazon
2024-10-17,188.220001,188.940002,186.000000,187.529999,187.529999,25039400,Amazon
2024-10-18,187.149994,190.740005,186.279999,188.990005,188.990005,37417700,Amazon
2024-10-21,188.050003,189.460007,186.399994,189.070007,189.070007,24639400,Amazon
2024-10-22,188.179993,191.520004,186.975006,189.699997,189.699997,28110987,Amazon

In [5]:
from data_analysis import get_description

description_dict = get_description()
description_dict

{'nvda':               Open         High          Low        Close    Adj Close  \
 count  1713.000000  1713.000000  1713.000000  1713.000000  1713.000000
 mean     25.821331    26.310198    25.299084    25.830662    25.801825
 std      30.874512    31.468483    30.197902    30.866736    30.874650
 min       3.162250     3.249500     3.111500     3.177000     3.151646
 25%       6.184750     6.258500     6.086750     6.171250     6.124423
 50%      14.157000    14.354750    13.863500    14.160000    14.135490
 75%      27.375000    28.000000    27.101999    27.579000    27.560066
 max     142.919998   144.419998   141.779999   143.710007   143.710007

              Volume
 count  1.713000e+03
 mean   4.697213e+08
 std    2.093899e+08
 min    9.788400e+07
 25%    3.251240e+08
 50%    4.333300e+08
 75%    5.696850e+08
 max    2.511528e+09  ,
 'tsla':               Open         High          Low        Close    Adj Close  \
 count  1713.000000  1713.000000  1713.000000  1713.000000  1713.000000
 mean    152.712594   156.095063   149.101137   152.672930   152.672930
 std     108.677105   111.021857   106.062150   108.553335   108.553335
 min      12.073333    12.445333    11.799333    11.931333    11.931333
 25%      23.000000    23.372667    22.620667    23.054667    23.054667
 50%     179.899994   183.649994   175.580002   179.830002   179.830002
 75%     238.729996   244.080002   234.033340   238.830002   238.830002
 max     411.470001   414.496674   405.666656   409.970001   409.970001

              Volume
 count  1.713000e+03
 mean   1.285524e+08
 std    8.026247e+07
 min    2.940180e+07
 25%    7.913400e+07
 50%    1.054164e+08
 75%    1.489497e+08
 max    9.140820e+08  ,
 'amzn':               Open         High          Low        Close    Adj Close  \
 count  1713.000000  1713.000000  1713.000000  1713.000000  1713.000000
 mean    127.067426   128.561935   125.434907   127.028565   127.028565
 std      36.889689    37.206220    36.508868    36.837261    36.837261
 min      58.599998    59.500000    58.525501    59.450500    59.450500
 25%      92.253502    93.349998    91.074997    92.243500    92.243500
 50%     124.970001   126.580002   123.363503   124.897003   124.897003
 75%     161.249496   163.084000   159.500000   161.259995   161.259995
 max     200.089996   201.199997   199.050003   200.000000   200.000000

              Volume
 count  1.713000e+03
 mean   7.710581e+07
 std    3.974144e+07
 min    1.762600e+07
 25%    5.094190e+07
 50%    6.625800e+07
 75%    9.263800e+07
 max    3.113460e+08  ,
 'msft':               Open         High          Low        Close    Adj Close  \
 count  1713.000000  1713.000000  1713.000000  1713.000000  1713.000000
 mean    238.089498   240.400257   235.629818   238.127221   232.851084
 std     102.606730   103.340315   101.732714   102.583368   104.052632
 min      86.059998    86.309998    83.830002    85.010002    78.920250
 25%     138.660004   139.630005   136.910004   138.240005   131.925308
 50%     240.899994   243.250000   238.050003   240.979996   236.036331
 75%     309.630005   311.929993   306.459991   310.109985   303.950012
 max     467.000000   468.350006   464.459991   467.559998   466.718781

              Volume
 count  1.713000e+03
 mean   2.866290e+07
 std    1.241356e+07
 min    8.989200e+06
 25%    2.072010e+07
 50%    2.569180e+07
 75%    3.293560e+07
 max    1.112421e+08  ,
 'cost':               Open         High          Low        Close    Adj Close  \
 count  1713.000000  1713.000000  1713.000000  1713.000000  1713.000000
 mean    427.225306   431.018908   423.448074   427.475435   409.955298
 std     183.215901   184.691458   181.596384   183.274026   188.511337
 min     178.910004   182.070007   175.789993   178.610001   161.077347
 25%     287.489990   291.380005   283.179993   287.570007   264.301819
 50%     384.339996   386.579987   381.179993   383.910004   366.081512
 75%     530.710022   535.859985   525.549988   529.719971   511.259766
 max     922.000000   923.830017   909.359985   917.080017   917.080017

              Volume
 count  1.713000e+03
 mean   2.237315e+06
 std    1.044899e+06
 min    5.436000e+05
 25%    1.596800e+06
 50%    1.952500e+06
 75%    2.489400e+06
 max    9.511600e+06  ,
 'gme':               Open         High          Low        Close    Adj Close  \
 count  1713.000000  1713.000000  1713.000000  1713.000000  1713.000000
 mean     16.827585    17.647137    16.043449    16.770962    16.720007
 std      16.151248    17.186322    15.119281    15.980011    16.021935
 min       0.712500     0.735000     0.642500     0.700000     0.700000
 25%       2.890000     2.965000     2.830000     2.892500     2.802418
 50%      14.152500    14.610000    13.820000    14.230000    14.230000
 75%      25.665001    26.740000    24.520000    25.434999    25.434999
 max      94.927498   120.750000    72.877502    86.877502    86.877502

              Volume
 count  1.713000e+03
 mean   2.269050e+07
 std    5.126804e+07
 min    1.122700e+06
 25%    5.372000e+06
 50%    1.097960e+07
 75%    1.967720e+07
 max    7.886316e+08  ,
 'pfe':               Open         High          Low        Close    Adj Close  \
 count  1713.000000  1713.000000  1713.000000  1713.000000  1713.000000
 mean     38.436035    38.825334    38.036840    38.431042    33.393290
 std       7.134746     7.258444     7.028525     7.158234     6.621292
 min      25.330000    25.459999    25.200001    25.260000    22.386389
 25%      34.089184    34.392788    33.766602    34.089184    28.472963
 50%      37.020000    37.360001    36.680000    37.009998    31.395676
 75%      41.755219    42.115749    41.423149    41.755219    36.969963
 max      60.599998    61.709999    59.830002    61.250000    54.310184

              Volume
 count  1.713000e+03
 mean   2.896111e+07
 std    1.547528e+07
 min    5.187683e+06
 25%    1.979591e+07
 50%    2.501300e+07
 75%    3.318920e+07
 max    2.301539e+08  ,
 'lly':               Open         High          Low        Close    Adj Close  \
 count  1713.000000  1713.000000  1713.000000  1713.000000  1713.000000
 mean    295.521661   298.873292   292.077443   295.591751   289.191918
 std     231.836715   234.297137   228.856132   231.615478   233.900409
 min      75.059998    76.230003    73.690002    74.209999    66.461128
 25%     118.400002   119.529999   117.230003   118.639999   109.849251
 50%     208.240005   211.839996   204.779999   207.570007   199.160522
 75%     359.070007   362.799988   355.170013   359.869995   354.404053
 max     957.770020   972.530029   951.580017   960.020020   960.020020

              Volume
 count  1.713000e+03
 mean   3.973602e+06
 std    4.709437e+06
 min    6.272000e+05
 25%    2.399800e+06
 50%    3.058600e+06
 75%    4.200600e+06
 max    7.482250e+07  }

In [9]:
# Sample data for a few days
data = {
    'Date': ['2023-10-20', '2023-10-23', '2023-10-24', '2023-10-25', '2023-10-26'],
    'Open': [120.5, 121.5, 122.0, 121.8, 123.0],
    'High': [121.0, 123.0, 123.5, 122.5, 124.0],
    'Low': [119.8, 120.5, 121.2, 120.8, 122.0],
    'Close': [120.8, 122.5, 122.2, 121.5, 123.5],
    'Volume': [1500, 2200, 1800, 1300, 2100]
}

# Convert the data into a DataFrame
df = pd.DataFrame(data)
df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)

# Plotting the candlestick chart
mpf.plot(df, type='candle', style='charles', title='Candlestick Chart', ylabel='Price', volume=True)

NameError: name 'mpf' is not defined

In [6]:
STOCK_LIST =  ['NVDA', 'TSLA', 'AMZN', 'MSFT', 'COST']

stocks_dfs_dict = {}

for symbol in STOCK_LIST:
    file_name = f"{symbol.lower()}_stock.csv"
    path_csv = f"data/{file_name}"
    stocks_dfs_dict[f"{symbol.lower()}"] = pd.read_csv(path_csv,index_col='Date')

FileNotFoundError: [Errno 2] No such file or directory: 'data/nvda_stock.csv'

In [ ]:
type(stocks_dfs_dict)
stocks_dfs_dict["nvda"].describe()