In [1]:
import pandas as pd

In [50]:
STOCK_LIST =  ['NVDA', 'TSLA', 'AMZN', 'MSFT', 'COST']

stocks_dfs_dict = {}

for symbol in STOCK_LIST:
    file_name = f"{symbol.lower()}_stock.csv"
    path_csv = f"data/{file_name}"
    stocks_dfs_dict[f"{symbol.lower()}"] = pd.read_csv(path_csv,index_col='Date')

In [51]:
type(stocks_dfs_dict)
stocks_dfs_dict["nvda"].describe()

,Open,High,Low,Close,Adj Close,Volume
count,1706.000000,1706.000000,1706.000000,1706.000000,1706.000000,1.706000e+03
mean,25.360235,25.842122,24.845710,25.369463,25.340507,4.705667e+08
std,30.084276,30.670110,29.415329,30.075233,30.082945,2.093667e+08
min,3.162250,3.249500,3.111500,3.177000,3.151646,9.788400e+07
25%,6.183625,6.250188,6.074687,6.163750,6.119212,3.258720e+08
50%,14.087625,14.340875,13.770625,14.131500,14.109439,4.344320e+08
75%,27.292250,27.782001,26.809751,27.341500,27.302633,5.701892e+08
max,139.800003,140.759995,133.660004,135.580002,135.568405,2.511528e+09